### ISSUE TITLE
Implement Drag And Drop

### ISSUE THREAD

**Issue by FooOperator** [FooOperator/tier-list#1]
Drag and drop the entries - From unranked to tier, and from tier to tier. Should not break grid formation, and should remove the item from the list and transfer to the drop list.

**Comment by RoySounak** [comment]
@FooOperator Hi, do you want to implement drag and drop functionality in the app?
If yes, I would like to contribute

**Comment by FooOperator** [comment]
@RoySounak yes, I would like that. Currently working on the context menu, so our work shouldn't overlap.

**Comment by RoySounak** [comment]
@FooOperator  Yes, that's right. We will discuss on which component i need to work and after that I will start to work on newly created different branch then it will not  overlap.

**Comment by FooOperator** [comment]
@RoySounak brother, sorry for the wait, unfortunately I've already added dnd function because I needed to do some refactoring so I took the chance. I still thank you for offering the help! We could collab later down the line.

**Comment by FooOperator** [comment]
DnD function partially added, will work more on in it later.
